const wordList = [
  // Level 1: Alphabet (A-Z)
  { en: "A", ja: "A", category: "alphabet", level: 1 },
  { en: "B", ja: "B", category: "alphabet", level: 1 },
  { en: "C", ja: "C", category: "alphabet", level: 1 },
  { en: "D", ja: "D", category: "alphabet", level: 1 },
  { en: "E", ja: "E", category: "alphabet", level: 1 },
  { en: "F", ja: "F", category: "alphabet", level: 1 },
  { en: "G", ja: "G", category: "alphabet", level: 1 },
  { en: "H", ja: "H", category: "alphabet", level: 1 },
  { en: "I", ja: "I", category: "alphabet", level: 1 },
  { en: "J", ja: "J", category: "alphabet", level: 1 },
  { en: "K", ja: "K", category: "alphabet", level: 1 },
  { en: "L", ja: "L", category: "alphabet", level: 1 },
  { en: "M", ja: "M", category: "alphabet", level: 1 },
  { en: "N", ja: "N", category: "alphabet", level: 1 },
  { en: "O", ja: "O", category: "alphabet", level: 1 },
  { en: "P", ja: "P", category: "alphabet", level: 1 },
  { en: "Q", ja: "Q", category: "alphabet", level: 1 },
  { en: "R", ja: "R", category: "alphabet", level: 1 },
  { en: "S", ja: "S", category: "alphabet", level: 1 },
  { en: "T", ja: "T", category: "alphabet", level: 1 },
  { en: "U", ja: "U", category: "alphabet", level: 1 },
  { en: "V", ja: "V", category: "alphabet", level: 1 },
  { en: "W", ja: "W", category: "alphabet", level: 1 },
  { en: "X", ja: "X", category: "alphabet", level: 1 },
  { en: "Y", ja: "Y", category: "alphabet", level: 1 },
  { en: "Z", ja: "Z", category: "alphabet", level: 1 },

  // Level 2: Numbers (1-20), Colors
  { en: "One", ja: "1", category: "number", level: 2 },
  { en: "Two", ja: "2", category: "number", level: 2 },
  { en: "Three", ja: "3", category: "number", level: 2 },
  { en: "Four", ja: "4", category: "number", level: 2 },
  { en: "Five", ja: "5", category: "number", level: 2 },
  { en: "Six", ja: "6", category: "number", level: 2 },
  { en: "Seven", ja: "7", category: "number", level: 2 },
  { en: "Eight", ja: "8", category: "number", level: 2 },
  { en: "Nine", ja: "9", category: "number", level: 2 },
  { en: "Ten", ja: "10", category: "number", level: 2 },
  { en: "Eleven", ja: "11", category: "number", level: 2 },
  { en: "Twelve", ja: "12", category: "number", level: 2 },
  { en: "Thirteen", ja: "13", category: "number", level: 2 },
  { en: "Fourteen", ja: "14", category: "number", level: 2 },
  { en: "Fifteen", ja: "15", category: "number", level: 2 },
  { en: "Sixteen", ja: "16", category: "number", level: 2 },
  { en: "Seventeen", ja: "17", category: "number", level: 2 },
  { en: "Eighteen", ja: "18", category: "number", level: 2 },
  { en: "Nineteen", ja: "19", category: "number", level: 2 },
  { en: "Twenty", ja: "20", category: "number", level: 2 },
  { en: "Red", ja: "あか", category: "color", level: 2 },
  { en: "Blue", ja: "あお", category: "color", level: 2 },
  { en: "Green", ja: "みどり", category: "color", level: 2 },
  { en: "Yellow", ja: "きいろ", category: "color", level: 2 },
  { en: "Black", ja: "くろ", category: "color", level: 2 },
  { en: "White", ja: "しろ", category: "color", level: 2 },
  { en: "Pink", ja: "ピンク", category: "color", level: 2 },
  { en: "Orange", ja: "オレンジ", category: "color", level: 2 },
  { en: "Purple", ja: "むらさき", category: "color", level: 2 },
  { en: "Brown", ja: "ちゃいろ", category: "color", level: 2 },

  // Level 3: Nouns (Family, School, Food, Animal)
  { en: "Father", ja: "おとうさん", category: "family", level: 3 },
  { en: "Mother", ja: "おかあさん", category: "family", level: 3 },
  { en: "Brother", ja: "きょうだい", category: "family", level: 3 },
  { en: "Sister", ja: "しまい", category: "family", level: 3 },
  { en: "Grandfather", ja: "おじいさん", category: "family", level: 3 },
  { en: "Grandmother", ja: "おばあさん", category: "family", level: 3 },
  { en: "Teacher", ja: "せんせい", category: "school", level: 3 },
  { en: "Student", ja: "せいと", category: "school", level: 3 },
  { en: "School", ja: "がっこう", category: "school", level: 3 },
  { en: "Desk", ja: "つくえ", category: "school", level: 3 },
  { en: "Chair", ja: "いす", category: "school", level: 3 },
  { en: "Pencil", ja: "えんぴつ", category: "school", level: 3 },
  { en: "Book", ja: "ほん", category: "school", level: 3 },
  { en: "Bag", ja: "かばん", category: "school", level: 3 },
  { en: "Lunch", ja: "ひるごはん", category: "food", level: 3 },
  { en: "Rice", ja: "ごはん", category: "food", level: 3 },
  { en: "Bread", ja: "パン", category: "food", level: 3 },
  { en: "Milk", ja: "ぎゅうにゅう", category: "food", level: 3 },
  { en: "Egg", ja: "たまご", category: "food", level: 3 },
  { en: "Apple", ja: "りんご", category: "food", level: 3 },
  { en: "Banana", ja: "バナナ", category: "food", level: 3 },
  { en: "Orange", ja: "オレンジ", category: "food", level: 3 },
  { en: "Cat", ja: "ねこ", category: "animal", level: 3 },
  { en: "Dog", ja: "いぬ", category: "animal", level: 3 },
  { en: "Bird", ja: "とり", category: "animal", level: 3 },
  { en: "Fish", ja: "さかな", category: "animal", level: 3 },
  { en: "Rabbit", ja: "うさぎ", category: "animal", level: 3 },
  { en: "Lion", ja: "ライオン", category: "animal", level: 3 },
  { en: "Elephant", ja: "ぞう", category: "animal", level: 3 },
  { en: "Monkey", ja: "さる", category: "animal", level: 3 },

  // Level 3: Greetings/Others
  { en: "Hello", ja: "こんにちは", category: "greeting", level: 3 },
  { en: "Good morning", ja: "おはよう", category: "greeting", level: 3 },
  { en: "Good night", ja: "おやすみ", category: "greeting", level: 3 },
  { en: "Thank you", ja: "ありがとう", category: "greeting", level: 3 },
  { en: "Happy", ja: "うれしい", category: "emotion", level: 3 },
  { en: "Sad", ja: "かなしい", category: "emotion", level: 3 },
  { en: "Sunday", ja: "にちようび", category: "time", level: 3 },
  { en: "Monday", ja: "げつようび", category: "time", level: 3 },
  { en: "Spring", ja: "はる", category: "season", level: 3 },
  { en: "Summer", ja: "なつ", category: "season", level: 3 },
  { en: "Autumn", ja: "あき", category: "season", level: 3 },
  { en: "Winter", ja: "ふゆ", category: "season", level: 3 },
  { en: "I", ja: "わたし", category: "pronoun", level: 3 },
  { en: "You", ja: "あなた", category: "pronoun", level: 3 },
  { en: "He", ja: "かれ", category: "pronoun", level: 3 },
  { en: "She", ja: "かのじょ", category: "pronoun", level: 3 }
];
